class PayloadsUpdateOrderInOneCrm:
    """Отправляемые данные на /api/Offer/UpdateOrderInOneCrm"""

    false = False
    true = True
    null = None

    update_order_basic = {
        "Completed": "1",
        "Deleted": "0",
        "Date": "string",
        "DocumentNumber": "string",
        "ContractNumber": "",
        "PaymentTermsCode": "RU00",
        "HeadOffice": "",
        "PartnerSAPID": "",
        "PartnerINN": "",
        "PartnerNamе": "",

        "Organization": {
            "ContractorId": "19b59c30-cf60-4000-8fd0-30fc6821a301",
            "INN": "string",
            "ContractorName": "string",
            "Approvers": []
        },

        "Currency": "RUB",
        "TotalAmount": 0,
        "Warehouse": "0010 Склад Лешково ",
        "TaxIncluded": "0",
        "ResponsibleEngineer": "",
        "AddlInfo": "",
        "CompleteDelivery": false,
        "Status": "К выполнению / В резерве",
        "PrepayAmountToCollect": 0,
        "PrepayAmountToDelivery": 0,
        "DeliveryDate": "",
        "DeliveryAddress": "",
        "TaxType": "Продажа облагается НДС",
        "DelayedDeliveryDiscountValue": 0,
        "DeliveryCost": 0,
        "DiscountsCalculated": "1",
        "EngineerComment": "test_update_order_in_one_crm",
        "ReferenceNumber": "Z0000052452",
        "ReferenceDate": "",
        "QuotationNumber": "string",
        "Consignee": "",
        "ConsigneeSAPID": "",
        "ConsigneeName": "",
        "SalesDepartmentName": "",
        "SalesDepartmentCode": "",
        "Author": "0000612383",
        "DeliveryType": "Pickup",
        "DeliveryPartner": "",
        "DeliveryAddressValue": "",
        "DeliveryAddlInfo": "",
        "ContactPerson": "",
        "SalesGroup": "RU1",
        "PaidInCurrency": "0",

        "Materials": [
            {
                "LineNo": 1,
                "DeliveryDate": "",
                "ODID": "19b59c30-cf70-4000-8a50-792e49739201",
                "MaterialNumber": "003L0144R",
                "MaterialName": "string",
                "PackType": "шт",
                "PacksAmount": 25,
                "AmountInWareUnits": 25,
                "ItemQuantityInCollection": 0,
                "CollectionQuantity": 0,
                "PriceCondition": "",
                "Price": 0,
                "Amount": 0,
                "Tax": "20%",
                "TaxAmount": 0,
                "AmountWithTax": 0,
                "DiscountPercent": 0,
                "DiscountAmount": 0,
                "AutoDiscountPercent": 0,
                "CancelReason": "",
                "Code": 1,
                "Cancelled": "0",
                "RelationshipKey": 0,
                "Description": "string",
                "Warehouse": "0010 Склад Лешково ",
                "DeliveryDays": 0,
                "SupplyType": "Отгрузить",
                "CollectionTypeNumber": "",
                "CollectionTypeName": "",
                "SalesDepartmentName": "",
                "SalesDepartmentCode": "",
                "Stock": 0,
                "Reservation": 0,
                "OnStock": 0,
                "Transit": []
            }
        ],

        "StagesSchedulePayment": [],
        "CompleteDeliveryFrom": "1970-01-01T00:00:00.000Z",
        "PaidStorage": [],
        "Errors": [],
        "CurrentStatus": "Готов к отгрузке",
        "PaymentPercent": 0
    }